### ISSUE TITLE
warps limit per factions

### ISSUE THREAD

**Issue by alexsatellite** [MarkehMe/FactionsWarps#1]
Can you add a limit of warps per faction and a price (If the limit 3 and you try to set your 4º warp you'll get an error.)

**Comment by markhughes** [comment]
Sure, this can be implemented:
- [x] ~~Economy (Vault Integration)~~
- [x] ~~Warp Limitations (permission-based?)~~

**Edit: Done**

**Comment by alexsatellite** [comment]
if you need help to finish this I can help you a little bit (I'm kinda bussy).

**Comment by markhughes** [comment]
I'll do it today 😄

**Comment by markhughes** [comment]
So I've added some basic functionality, I need to extensively test it still.

**Comment by alexsatellite** [comment]
I made a copy into my repository for add some modifications. The first thing I added is a checker for the move event, because this event is fired every time you move your mouse, not only when you move from one block to other. This one was very easy, I'll keep fixing things thought. Also saving the Pitch and Yaw is more "stetic/smoother" when you teleport.

```
if ((event.getFrom().getBlockX() != event.getTo().getBlockX()) || (event.getFrom().getBlockZ() != event.getTo().getBlockZ())){
        this.pingWarmup(event.getPlayer());
            }
```

**Comment by markhughes** [comment]
Thats great! This is something I used to do in FactionsPlus. Not sure why I didn't implement the same thing. Thank you! 😄 

Please feel free to create a pull request with that, or I will just throw it in later.

**Comment by markhughes** [comment]
🎉  **FactionsWarps v1.1.0 has been released and addresses this issue** 🎉 

You can grab it from:
- [Spigot Resources](https://www.spigotmc.org/resources/factionswarps.22510/update?update=89457)
- [BukkitDev](http://dev.bukkit.org/bukkit-plugins/factionswarps/files/2-factions-warps-v1-1-0/)

```
v1.1.0 Changelog:

* Added passwordsCaseSensitive option
* Allow migrating from FactionsUUID
* Allow removing FactionsUUID warp commands
* Vault/Economy integration
* Added Events API
* Fix configuration bug with warp command
```
