### ISSUE TITLE
Cant Create More Than 7 Warps

### ISSUE THREAD

**Issue by CapnCranch** [MarkehMe/FactionsWarps#17]
Players on my server cant make more than 7 warps and i thought it was a config thing but it wasnt so im guessing its a bug

**Comment by markhughes** [comment]
7 warps is a very specific number! My best guess is that you have assigned the permission `factionswarps.warplimit.7` to the leader. Can you check the permission?

**Comment by CapnCranch** [comment]
They didnt have that permission

**Comment by markhughes** [comment]
What is the warp limit?
