### ISSUE TITLE
Not able to use warps unless OFFICER

### ISSUE THREAD

**Issue by VerumUK** [MarkehMe/FactionsWarps#5]
My players aren't able to use the warps unless they're Officer in the Faction. No errors displayed in console, they just get the reply "You must be of at least an Officer in your faction to use this command"

Faction version: 2.8.8
Framework: 1.0.0
Warps: 1.0.0
Config: http://pastebin.com/8a0PesKp

**Comment by markhughes** [comment]
Thanks for reporting, fixed.

**Comment by markhughes** [comment]
🎉  **FactionsWarps v1.1.0 has been released and addresses this issue** 🎉 

You can grab it from:
- [Spigot Resources](https://www.spigotmc.org/resources/factionswarps.22510/update?update=89457)
- [BukkitDev](http://dev.bukkit.org/bukkit-plugins/factionswarps/files/2-factions-warps-v1-1-0/)

``````
v1.1.0 Changelog:

* Added passwordsCaseSensitive option
* Allow migrating from FactionsUUID
* Allow removing FactionsUUID warp commands
* Vault/Economy integration
* Added Events API
* Fix configuration bug with warp command```
``````
