### ISSUE TITLE
Registered factions version incorrect

### ISSUE THREAD

**Issue by VerumUK** [MarkehMe/FactionsWarps#6]
Factions: 2.8.8
Factionwarps: 1.1.0
Frameworks: 1.1.0

Console error: http://pastebin.com/BcWpGA5P

**Comment by markhughes** [comment]
This is a bug in FactionsFramework - was not aware 2.8.8 had major changes. Testing this now.

**Comment by markhughes** [comment]
Please follow that ticket in the FactionsFramework repo for updates. 😃

**Comment by markhughes** [comment]
🎉  **FactionsFramework v1.1.1 has been released and addresses this issue** 🎉 

You can grab it from:
- [GitHub](https://github.com/MarkehMe/FactionsFramework/releases/tag/v1.1.1)
- [Spigot Resources](https://www.spigotmc.org/resources/factions-framework.22278/update?update=89723)
- [BukkitDev](http://dev.bukkit.org/bukkit-plugins/factionsframework/files/3-factions-framework-v1-1-1/)

```
v1.1.1 Changelog:

* Added a missing 1.8 Layer
* Added new 2_8_8 layer support Factions 2.8.8 and newer versions
* Minor 2_8_6 layer fixes
```
