### ISSUE TITLE
Deleting warps not working

### ISSUE THREAD

**Issue by tehrenderr** [MarkehMe/FactionsWarps#7]
/f removewarp isn't a command and is not working properly with the latest version of factionwarps and factionsframework.

**Comment by markhughes** [comment]
What is your Factions version?

I was able to delete my warp. Could you please share your server log showing you executing the command? _Please_ include a few lines above and below, also any stack traces if there are any errors. 

The entire list of aliases are:
- /f deletewarp <name>
- /f removewarp <name>
- /f delwarp <name>
- /f remwarp <name>

Have you assigned yourself the permission `factions.warp.manage`

---

![](http://i.imgur.com/CjLk31v.png)

```
[16:17:11 INFO]: MarkehMe issued server command: /f setwarp test
[16:17:12 INFO]: MarkehMe issued server command: /f warps
[16:17:15 INFO]: MarkehMe issued server command: /f warp test
[16:17:23 INFO]: MarkehMe issued server command: /f deletewarp test

```

**Comment by tehrenderr** [comment]
Found the error, http://pastebin.com/tX1qpUi9

**Comment by markhughes** [comment]
Do you specify an argument? e.g. `/f deletewarp storage`

**Comment by tehrenderr** [comment]
The error only pops up when I don't specify an argument. When I do specify an argument it does this:
https://gyazo.com/903e52e76fe50e5833ed99fe542f2b15

**Comment by markhughes** [comment]
I see, this must be a problem with the arguments being added. 

Can you try this build of FactionsFramework? It attempts to add arguments a different way. 

[FactionsFramework-1.1.2-SNAPSHOT.jar.zip](https://github.com/MarkehMe/FactionsWarps/files/269528/FactionsFramework-1.1.2-SNAPSHOT.jar.zip)

**Comment by tehrenderr** [comment]
Nope didn't work. Still got the same errors without arguments and with arguments it didn't do anything and just gave the "Use the command like this:" message.

**Comment by markhughes** [comment]
What is your version of Factions and MassiveCore?

**Comment by tehrenderr** [comment]
2.7.5 factions and massivecore

**Comment by markhughes** [comment]
I've been able to replicate this bug in 2.7.5, I'm releasing a temporary fix. This is an external bug in FactionsFramework.

**Comment by markhughes** [comment]
Temp fix is in latest FactionsWarps source. Bug should be followed upstream for now.
